# advent of code https://adventofcode.com/2022
# Day 3


test_data = ("vJrwpWtwJgWrhcsFMMfFFhFp",
        "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL",
        "PmmdzqPrVvPwwTWBwg",
        "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn",
        "ttgJtRGJQctTZtZT",
        "CrZsJsPPZsGzwwsLwLmpwMDw")

data = (
  "BdbzzddChsWrRFbzBrszbhWMLNJHLLLLHZtSLglFNZHLJH",
"nnfMwqpQTMffHlNNLllHnZSS",
"cGpcMwfppfqcjcTCBBzWDsDbDrjzWz",
"LhfjhcdjcGdhFfdGfdjdvwCCZMvvLvWwMLCLSwZC",
"rDnsbmptPmlbQMCrQWQQBZQW",
"gltgVPngDPbptPsbPzVgmDldfTdfczThjJJjfMcJdFHjjH",
"dGlgDflTLLLrRLTLVdQLcQMnbvHbbFzNNvMbnHHn",
"sZjWJJCSjWqfCqSjSmJSbFvCzBMBBzHncHNvMBHN",
"twqqwpZwfrlwRwDGDR",
"zCGGFTQMQrsNRNGZdR",
"cLLQgPDpgcgmvPRHrwBdvrNZ",
"glWpmJWQDcJpQnpjSmbhFtMnqFfCVTCFCFFM",
"zNZWFNZBFrGTdBcZZBdJTrGrmgvppgDHwHmgVHCHCvCPDjzC",
"qtqqPnLSfLwvjvvgvvqH",
"MtbLLLQbRfPRfnbnnLMtnsbdBNsrGWNWcNcTBWZrrcrWcJ",
"sZwstbbDVlHtbhcrhhZLrRpNQN",
"jqGjjFjWnzWGgqWjJJNphnLMRhLhcrhcrSLN",
"qCJzFJdvmHvbtpbb",
"ZSRsvvQvZpsRQGJghClPCwGPChCP",
"FVdMLDdtDRdDcBtmcVFntwgJJTlnNPwJnlTlwlTPgN",
"VqttMWFmDbjbzrSWRQ",
"TsDSBcwshdwSCrgRWZBvgGRG",
"LPVJLqqJbbzpFqwpbvgGRmZPrmZgCvCCfr",
"tzJlJzQllFLqtwHhjNSdtthjDhTN",
"fsDLDDnwvnSdqLSsFSDfsLpbgVttPMpPNjMWVMNfpjgW",
"jhHmBmlrTBBHRPVtMZbppNPPZB",
"JmTTrTmjRTJqSQQSFqQw",
"HPzZFgPFMCHJCcZMcDQGwpLqPLqppwhGvv",
"BrWRqbqRsTSTqNddrVrthLQVwnpwphnvnDnGvGDn",
"tSbBfsRbTfqjJqjCqm",
"pCqrqzmqZzrmCCvCJwJPBRwJBWBmwWBJ",
"VqbqbjFLFfSHnfctBwDdDFTwtRRTDF",
"LVcnbjHLSqHnhbSGGppCMMZMphpNrQ",
"PhTcTPsSPCMvvhhMRPttbNWfNsWFNfWWtpNw",
"rdQrDbJBVVjrBVdLjHHHWNWwfHtzzNtFpZZptppg",
"JJVGGdddjDjDJmdjGqqRSbPMTvcRlqnnMlvT",
"SqGfTrBlSrrrfGGQvCnqZhZmPPhvJh",
"LdVNwgsjdjHmjWwDsDpwsHWtnCnQQQQNnvCnbJZQbNbtZZ",
"DjssDHLLVppDssdLspswFLVjzfFMTfSBcTRcrFSBzBTzmGzr",
"JSJJqlldpJlcdVWMlgMJrcCjrhzHCwTjHrQzwTzZ",
"bBvsGBGNFDNRFNFBRDPsDDHCChhhrZRQQzhjhCjTzWCr",
"FvbLFGDDtWDFBnPGFDWGqJMgJpSdVStllttlppVS",
"clpBdBQBsqGpQbVdqTTWRTSFgLLggffg",
"NzvwmHvZtZZgbDSCLDmfmm",
"jPJjthHzNwPvvjwjNzPzztZBlrccpbVGBQhlGBVlrpnpBs",
"NmFFGlGmzCrNWHvFmFWCFvQPTdDDlbbdgJPtgbbdPDcc",
"RwfBqLwZqffqnPbdDgVQDdtRbT",
"hnptqLMMLwqjMMjzSzHmhvNNrvvhhz",
"hqVrDdPdVDqjsDrjjqsfrrWlctvHJNLfvNcLHNNZRNZHvfZL",
"CSnWQSGBBSnmBnTmSbQbNZZMJNJMccGNHLZNNvNv",
"gFnmBmBnTCpwmBbgWVqjPsrsjplVrjlqPr",
"vgVgJJCphzFjzbwljwww",
"PWmfDgrPrPWlSWqSWlSZ",
"rrTHQTGTPHDDHgPrcrcPmDPhdtGvnvNnttJCdJhtGVnpdM",
"DDDhNgWNLWgDqDgtgtwSngjVSQdf",
"cvFrcGmBrrrCdSfSJQ",
"mBHzFFvFzmsBspsFsZqhqbWlWdPDlLHbqZ",
"TLNpGpRzwGQLLQRTwdvWdWbdbgdBlblb",
"FJDVzZzHfZHVzcHgnvHnvngvvc",
"MzDVSmZPPrqhGmCqQqLR",
"mqHWcBHVcgsbhhnTrrTg",
"fWftGtfJpwJMSdFDLFSGDGFnnNrbrhTNsZnrhTswZZnnsb",
"dSftppdSFStLDpQfLjWHQvWBmmqVjCqcVv",
"frfNzgvzzzJwJqpRcP",
"VdVSnGnHqhDDTdqhdLWmjMTmjMPjPmTsmsmjmR",
"BdGLSWtBSWDtVqdSDVGqtSSHFZFZtQbZlZfNgFffrgNrvgrl",
"jBVSjsJcLcqqjtgcmRFRNFFzFm",
"CnHnWQQGGWnnCnfvCTmZRZgNtfZtNDZPtNDtzl",
"mWWGGdmQQWwrHHMBBBhrBVqshBLBSL",
"cLtFcllvrslGLcLHVzDZQzzpznWzQtQZ",
"TmShfSSPJRRBBfSgmdfBJhDNVpGzVZpzQgZgbWzpnDGp",
"BhJPfSqdhqJRdBdPqTJBChvrFlHvvCGCccHsMscvrHvv",
"zfddZTpZLzLDfLtDCttdTfZPnlcPcnhjPDnlcjMchDPjnP",
"MQsFvFHJsQvmNvvswljgbPbwlwjnmcch",
"VFVqvqFQHqVJRVCBLpqTGMzCqtMZ",
"PZdVgNdQQcdcZQtGhnHtBlvlvWTnbBHWWH",
"CDJmzqFmMmLfqmzFwqfzfwMRvpRbTWBBWDnlnbnWnTNTnB",
"zFfffjCqwLJCfrCFjCLCzCMsjSZjQNPhQGVSQQZhsGjGgd",
"nbHntnqPQwTHwQVC",
"BzfSZSpcBZpzpPhSBjRTCBWTTRWTTTWR",
"pvZpzPzNfhddJGmmNnJb",
"GwTgWlvbgTwMrbwTrlWvwtHBNtNvBhBtdZcShHDtNS",
"PnndmnCmnJFnsmRdmFnnZDhRRScRQQHDtDNtcDQS",
"CLffLsmqqpJljVdlpMpWlr",
"dPCzBLTSLqmqdSCsmrTDVQjZfjfVVZnZhhhLGQ",
"wwFpgvPJNwgPPwvZGnQhbZQQFfQZbf",
"WvRwwJpHHgpNMNqdTdCdqrmHBPtm",
"DbWwjSGFSFfwGfCwDSSPPjLhgrrLWRJRgggJphLzpJLq",
"lQTnMHdcQBvlHMMZBcHHTrbzpdzgqrpLdqzzVRVRVV",
"vlvlNlBQvBZTQBnHnQTTBBPwPNCCsfSFmbSFfmGPwFmj",
"hGGQtbVjhRqlmqqrmDlpmw",
"gPMZsMgdssCPPsvrgZcTZTPSnnLLnBWDwLmwWwBnmWSnWNWB",
"TsvgMPdcgCfMdcsZJRQhVfVRVQFFQGtr",
"NfpFTTpFNbpZMRFrJMMMCv",
"dWJPngDWBtPVBdPVGHZzCGHZrrvZRSMSzv",
"WDDDVDPlWnLBVgnsgJmQJNqThNmbjlqbbh",
"vnznqvfrzzVzrvvnfVqztBtGbMCdGmCcdccJccCLCcpSSgcL",
"RQsDsljDlhssWshHhlhsHTlLbgJLpmgbbcMSpSSbcSJgjd",
"WswhhHWlRTsQDwWHTRhsvNVvwqzfVmNBtZNmnzzq",
"cjcPfLlQtPsZQlfHZJqVSFdVwmSRRqSSddwDvF",
"MgNbBgzgnwdPRFmSPn",
"CMGbNNMhCMzzPzBpTNPGBclLcLfsptHQfQlZssLcLf",
"slsdfpSlllpTVJJGgGDgHMdV",
"wrBQrbQrhQcpbQrhLwRBrjVVgGGPgZMtZMVhgMPMGHPg",
"QQwRnrwRbbRcmQmrjRnjpvNsNTNSlTmsTqCSvsNSWz",
"GWNwppdHdpmzgPFPCRmlCBPB",
"bSrJhJSsMhrJMDPRCPBlwVCtVSLV",
"QbsbwqQZvrJhhQrhZZrhchTfnTWGNvWpNnjHGvGjNdGT",
"NMZGmnMBWmwmNnGwHrHvHzfrvrVVVj",
"pSbDRLgbpJDPpRZRQjjFqVhhDFjDVqfrzv",
"sQQscLTZcsTpRsBnmlBcdCMBMtlc",
"hwWslbGWbRvLZvcscZ",
"gQnmmrNTmSnTfgwDwVwpJvJPJzLqLJTLLvRcZz",
"mrmnSrDNNQSmmwdggrrDbHMGhtdtGhGlhtClMGhM",
"qQdlGcvDQDQvDdmtPmmmlStbjSrm",
"CpNhzWTCTRznBMvwtTjMrHtSvj",
"nWzsfZCsBhNpZLgGdQDddvqd",
"ggjTjJWDVVVRTwQcZWvchshWhs",
"LmFfLfSmBtCttNLfCFBPFNBvvvhrcQdvsrsdSwdqcwrwSw",
"CHttltmlPLMHRTgJQDgRDTMb",
"RPJgCdhgPPSzvWDcCfGHDcvf",
"HbrrwBspTwWDDnqbZjjD",
"rQrFsrsstQMQHJdHQm",
"GVwQVGBZBNQwsjdNcMMlgJNPgj",
"SWFfSzTCSWFCSpgnJLSjpMdc",
"FhTbvrzrMrDCVHsVsHGBtHwv",
"FsqjjVzFVWFqRRWBssdpNSBHwJpHHJJdddSN",
"lQgmhvbTcgTgfhTQhSCFCGJHSlwNtJdGHG",
"vgZPbbfMhbTmchhjRFRnsDRPWVqzWz",
"cvwfjjcJjqhctvSpCgCFVhrFCrpC",
"mRsQmsMlNNzznWQlRnsMRQlSCpLNbpwSSSrwFLDFLLLgFp",
"zznlnGlmRmMlPZnGQzMszMRfccTjcBJjtJtJjqTZtfwBTt",
"PtCwCCVqbjNNqqvGssPmHGsHMfPH",
"dcddcWFDJJJcLczhWQdcDScZvHZgpGfsvMfSmsggSvvnvM",
"TTQmTDhdQQzdRwjBVrRwCwBbBr",
"BnBsFHCrcnBrMBPSmMSCmrcFqnZLddLhdhdGLvqLqgqnLJJp",
"WfjTlNVDTtjzNWTlVMWNlTwTJphdgpvJLGLdgghZvGLpwddq",
"zVjbVblVDlNTlbzTzDjllDTzHmHCsmcMHcSBrCBbrHBcBPSC",
"ddlcGQlCjQNGQmPLslZTlmTtfT",
"MDzMwSwqpzpDRpWRJwgZhttrZmTPfZmrmtrMZZ",
"JSqRBpJzwgDDpqDqvpBRdCjbCjQCFCbHvdGPjdHQ",
"bwzPwGLZMsbJMPPLGLMQzbhhQRvWWtVqVhgCVtWWQDqt",
"HddrHFnFNpVnVLhnvLRV",
"NLdrFjHTBrrdjFSpFmNBmSfZMwZMJJfSffbwzwPbczbJ",
"QTWSzTTLwTfwflSNJRdvGlRGcNgJBl",
"FnmmqrqbBBgRbHGc",
"MFZqrCVCqmZCprspFZmnnMsDfzWzDwSfjSwPQPTLhffwBLwj",
"npfgFRTZRRnDZLdgRfRrrjcWzGpWGGGQrjjWpP",
"vblVbvSShhVzHWjzzlrPWG",
"bVwqvCBtShqBhCCtqhNqCJRTTBDFJJLnJgDRWFBnWg",
"nHDNQvgvnNZHDnsGcjfNTrTfVrfL",
"SRWFSBRLtSFqjTrVVcsVjTSG",
"BdBbRttWBdbdWdbppmZlLmgwHvgQvgLZ",
"PQRZlpDDptQSclBMGVBdhVFGBMpf",
"nnrsTCWjLJsnsSMShhGJfwffwV",
"vjzqsjqgSHbbtvHZ",
"DgFmbdSDZbPgLbDDmFwZwgLSfccGcGvnvvngsGGnsGMNWsWs",
"HqztHHhHVhHjhRRhJtCVBCfNprMWpcMMJfsvvMsGscpG",
"tjVtBVTBtHHqCRqtzQwTPSNdSwPTTbPFDdml",
"sbmBmHZbRRRmwBmsSjHzRjmSCNFLNLLQNQhFgtQLzNztlrff",
"MpqPPDPVnGqrJpcqqJpMVlgtlLFLChCgChCCQgCtCD",
"VdcVVJvdrVWHbwHWBSSBRb",
"tPDVBzzNSNdDSQpMQMTQJMMQMN",
"LqSWSmbsmfQTTGZMWGCW",
"cLjLcbrjqmvfqLbfmqLwDBBzSHPzlwzcdBlnnP",
"SbnHrGHSrrhHJBrrScDfcPDMfpPGcGcpDL",
"QTpmpmmQWlZsTvVQDMgggFLgFcPf",
"zsCNlltCslzlTNsNlShwdJCpSqdHrBhpwr",
"JZmFrmLGjFZdDGrrVTvzmPVvRRVzwzzl",
"WBnfMDBqMsgDBqpBvzwVlCwRTRRPpvlw",
"WfghfttggfSnnqbDftfqSBBDQdHhZFFJrrHFjGJdGjFrjQLj",
"rNLRjrlVlrFRJzlsjrVlRFGCmnMtftgCNDDgDmCfqNgPNM",
"SpdBpdHbpHWhZqnCdtCGggqCPn",
"QHHvvWwWhwVVQRscVzGl",
"QffLtMQGMQfDMMwMTJwqWHvH",
"nSSFznjFcfjTgVJTJjvT",
"RrBpcfSNpRBcFshrCtQrDGLPQb",
"GctcMldStGwPPbcLsQTV",
"jhnzDgnHnnfPVwHQTTLTds",
"gBgzDDhzvqdGGvrtdvtm",
"PPwRWVTvRvPVLwRpMlzmbmsbHWjbbs",
"dFTFCNfdjzjFjsMF",
"SgdffSTrnnqCgdqgcNrfSZqVvVLRDPJZQwJBLPQPtLZwJJ",
"HSzDQftHphTBHFhr",
"WMmJsMJNLWNPmmsncjMJcjtvwggVvhFFFhjrVwrjrjppvT",
"WWPsJJCWCtZZZRGC",
"SfFZQDRLgpLlRgQRRRFWTsbhBhgTjbWBjhshgw",
"tHVNGjtzzHvMMJJhrWJNrTrPbP",
"jvVVvGCGtCmjHtdHzQQfDpSSlDRnFfQFmR",
"ZBBPfVVPPrVmrWZJzNdPznbnbSzznP",
"gvgpGqFFMgMcGgwLwGpcJNZSTZbdbdzNNSlqbTnn",
"ssZLgsMLQvcFpVrhCsmtWHjrrW",
"nFvhRnWWzBRPHQqcqqCqmFbd",
"SJDJgVprLfDfbJmHmWWHQtJW",
"wVsgWVSTgLjfSsVjVBRvRNwwGGRhNZhRMZ",
"wTRrRBCTPTBPlgMqgHCqggHLgg",
"dmDzpQpBdmWmWzzzDFzjGNMSWLSgLVGGLVNSLgSg",
"JbFdmQQJpjpptQbdJJmDmdtnZhZRflTlnTrTlrhBwPPc",
"jwSwssQbwbStlhRgtsVstn",
"zPzFdFFZccPDgntzVHHgghRz",
"vVVdfFmZPDMWZZBmGQbwJJGCLwwMwJCS",
"PLLffLFqqNLwSffbnVzzRf",
"lsmgTggChrgDtZsZVblMVJMznVnwMBnb",
"hDZZTmZvhTgstvwNFdqpWQcqvP",
"mmWwpwqtmmHTqHpprRZQPPZLZWSFRFRB",
"gzcgscgbfvhRRNZQRRQPvr",
"JsjhcshCfJgrrpttTCTplH",
"TvNrvNrJfWWvtJLTHhvZZhQQwVGZZhbV",
"mFCPmBMPlPsPPBsMFPszbHQJwwHHhbZVQVzjhGHZ",
"qmlBsdCSmJBmsBBMnMMTDWDNcLrDprSNcWDNrW",
"HSnHCVqTddFHSVqFqdStSQGQwRzQCzCRzGRRGNPQwz",
"jhlBpgNvlfZjlfvmpgfgfBrMRRwMMPPLQMZRPMWMMZPQ",
"hflfpgjfBfDcpchlpvndbHFDdHqSqNVqNVdn",
"QBfhlVNfHSZHfVCVHSQfZfTCctdvdDTRtjDCtTRsjsvj",
"brrWWqzFWzwWbswDchhTRtDhjT",
"gbrFLnpzqrWPgqpLWrhnHGZlSfLfHfQBGVfHHNVG",
"hcFmVScmQBVhtcvfHLfvHSnbHRLn",
"lzQqlDqgpWPvJfRnlNJvww",
"PjCCCPgDgqGzmMtCQstZmBFs",
"GrnrHrmVVFMFhSSbSfhR",
"zjTqLtBjjdWdWTLshMZMDbPNRMSSqSPNfD",
"dTWjdtwWhjWTBzcnrpcwmQpCwcpw",
"BgtVBsgVVJhgGsSGJbghJqbsjLfZmLjmmtfZndNNZFFZNLdm",
"MHTlzlwHSvPvzMSPCTMQCNZdjjmnfQjdZfNLjF",
"HMDTwPDpzrTzpScBghDbVqRBgRBJsR",
"qjCsTmrrnnCmhcFrCjqmThRlbHGvJGvvvbRbbJRcQJRG",
"fVBBTfMdSZLNZgPdgglGRdbtbtJRllJWJtWb",
"TSZZSpNMPBLgpZLVgppBDFhzDmjrnzhjssFqDhzFnn",
"MDtDMWmMQmdzmMMqvlGfRcjzgpcPPjczPl",
"sZsHJWNJFJNbWFBhFBnnbVclbVVPglfcRggffGGpjl",
"srHWLNZZJdSLSdvDMw",
"BFqsPnsZcgnncggccqsqqpDPtDWPpPNTNSNThrWtSj",
"dQbfQQJJdwdmFRbJLRJdMrfDWrjpDrrprhDDDDNWWD",
"QGwdJmCFJZvGsvvncB",
"GRRNSjrffGTSPrNTffSgcJTwWJZbbZvwvwtVwWVJZv",
"CMcFsqmBQzMzshsBQBQvLWmJVwZtpJLJwJLvwt",
"qBzChnQlzMcRSnnRRjHGGg",
"dPPbPWNdTBbDpHPHpNsgzvFlglvHzvSFzCFF",
"fntqhGhRMhnnnGGCVMRhCVlSjswFvvjzjSzvQVSgsl",
"MMqqJJRCnMhZLCRhtPNrpZPDDWTDTrNBmD",
"VjVGNTNlNchVjNGRWrSWWtZtRrzncR",
"BTbbbwDmCDLTbDwfHmzZMmRrWtzPrZSZtrrz",
"qDLLqvwLBsfBbBdQFQTJhqThVTQJ",
"qBqPBGZflhrWznzZZdsnzv",
"FmHRcCCsCDwDbjtzdjWbdz",
"cTRwCCNHFNmwRgmFTNCFTJqqfqPJsPhPBlsrsfGf",
"JTNhhNrCTcWpJJcpWw",
"LLdLsfMsdStbtggLbnTpwfWDzpjvnnjzcz",
"MqSZsgbMbGFbZtgTSZSFSLhhmHlBQlmrmrPHHCPPZPBr",
"GgjjgpGvpJJtjgvPrJttsLjVwCsQsQNLsfLfMVCl",
"RddqZqzcZdSWcHdcqQfQLMwVflfNQNMQ",
"FncWTRcFlHWFmcFTgPJhGvDgpnnhhGtG",
"ZGPFJsPQCbZCCbgz",
"nrvrnGWTwwqTBRcpCRRg",
"DnGWDldNmSLSMdMQ",
"ScDmPPPmjmjjWgtdSmdmCnNqVQVVrNRTZTQTQDHHZGNH",
"wbbMhLvMJpRwJQrJGHqQGrQHqr",
"wzhspwpppswsMFLmtnzjdcmdPRWPtS",
"fPlLTtBlTjDbWcTMJcncWqss",
"LdvLrLpCRRQQmvhhVNpwRMWJZcFMZWJwJFFFwZsGcs",
"prrRVpvvRVNmRvvzHjHPlzPLSffbbPHS",
"bbCbzsQbBzbBFbFzFfJHfVJPfVPtzZttpm",
"hwvrjDDwjcDcvdnNvwdnwwDPpNtNMVtPpJpRmVMPfmtVZR",
"mmqDWjhcqhwvDDdTsSGGCbQGSBBLTGGl",
"wthtwrBQhhSrqJJVLMRPPtJLPF",
"vbmbZqfqgsfHmcllmLLJNLJMNFJNNvPGJn",
"jHlDscllClCCgbZzhWqBzBQzprWCqS",
"DwpDlwDwllhJwbDFNDwFPhDnQnZZzVVnnBrtNznzSSzZrr",
"MHPfWRTgWzTQmSTTZt",
"GdPjHLRMCfcGvwqDGbFq",
"NGdNpDPdNGLppLpwSNFFFDLwnnZbMnrHlHZQcHbcnHQcPcQM",
"jBgBsjssgjWJVGhBfhvJVnMlbnZQVrrrlHCcCZrl",
"sRBgvRffhhtvtBgvjgttWBJTLmFLLwdwzFdqLDDDqFGdLFTd",
"RBzRGRGBgnrPJrRGGWWbDggZTSTVZVFFSVZZdw",
"tfmLhjfshNNsqpppfjHdwVdQZbVbQFVVTmSVDV",
"jvqtwHqCNLNsNhNfjssLCzGJWcBRJRBCBBBrrWnGrG",
"cGDBdNFdNdDStNtGdGQGscDMvZjjZWMvMLjsjjLZjLsJLv",
"fbRnRzHVPClfRlbbmfHRlPvZvMLpqjvZJqZMpzMpZjBZ",
"gfbfBgCHCPVNhNGgTtFDcF",
"ljjvLZvvllFnlLJLJjLWFQrVssFpsGMFpNMGsr",
"qbHSqHTcHChqCmTSRqqBVpVdBQsVQQGHdMprWV",
"DbtcCqRhhTRmDnPMlLgfgztlZZ",
"QtMQzPZcbtGgTtLvtf",
"HwcDsdVVDnNSGLhwvffJvfTT",
"CSsdSHNmSDHcCqqcrrzQcC",
"nDNDfmMnmDJRNfJJdMDRBdwjcTtsSHvBTswTjwLtsCts",
"QcbQrZZggGWVVWbZZjStswCSCCttGCwLvC",
"ZgZgbzVglVbchVVrVhFWWpnnpNJmJMqDfMJnMRqNDDMD",
"WMfNvsjWGjsqFjqTRRQVJztDzVmJHbft",
"ZPhplcrLrmzQGzmz",
"ZPddLPlcSclhZChndMvgTjjWNGWMGWBj",
"nDLjMchghDcljfjffpfsqTmGCTGszGZVVzHV",
"wdFJPFrQRwSNbjVQCTGsHZHmHCHs",
"BRJJSddvdBrJwrBRNRFRSPRjvclLpWhpglgWpLplltnMgh",
"BbVRzMcpbMNMHMTJmWdljdlJjT",
"GtsqFnfvGSFqGfQvgnWWZlLlLjZWtWldPmlT",
"sSsFqsqsGghwQQmfGRHbbVczbwwBpBpHcw",
"BBFCBJCsGJBBgvgsvTlVhgNg",
"ZnLdjRQddLRnZrlScHRVTTSHhRvg",
"fnnjZLWdrnqdWrrPLddqVqBzGDJJFGCBDfJmbDzFMbmB",
)

"""
Lowercase item types a through z have priorities 1 through 26.
Uppercase item types A through Z have priorities 27 through 52.

"""
# Part 1

# Create list to iterate throw to get priority level
priority_key = (
  0,
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
)
priority_sum = 0
common = ""
common_item = ""

for rucksac in data:
  first_compartment = rucksac[0:len(rucksac)//2]
  if len(data)%2 == 0:
    second_compartment = rucksac[len(rucksac)//2:]
  else:
    second_compartment = rucksac[((len(rucksac)//2)+1):]
  for item in first_compartment:
    for item2 in second_compartment:
      if item2 == item:
        common = item2
  common_item += common

for i in range(len(priority_key)):
  for letter in common_item:
    if letter == priority_key[i]:
      priority_sum += i
  
print(f"Part 1: {priority_sum}")


#part 2

# create variable to store badge items by elf groups
elf_badge_list = ""

# creat elf_groups by steps of 3 
for i in range(0, len(data), 3):
  rucksac1 = data[i]
  rucksac2 = data[i+1]
  rucksac3 = data[i+2]

  # the strings are converted into sets and the common letters between the sets are found using the ‘&’ operator.
  # stored as a list in the variable badge
  badge = list(set(rucksac1)&set(rucksac2)&set(rucksac3))
  

  # convert badge to a string and add to variable elf_badge_list
  elf_badge_list += str(badge)

priority_sum2 = 0 

# get priority sum for elf_badge_list
for i in range(len(priority_key)):
  for elf_badge in elf_badge_list: 
    if elf_badge == priority_key[i]:
      priority_sum2 += i
  
print(f"Part 2: {priority_sum2}")